name: Build and Deploy to Test Branch
run-name: ${{ github.actor }} is deploying code to Github Pages 🚀

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed to push to another branch

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use your desired Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy dist to test branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Create a temp directory and copy only dist contents
          mkdir temp-dist
          cp -R dist/* temp-dist/
          echo "www.w3bl.co.uk" > temp-dist/CNAME

          # Switch to test branch (or create it)
          git checkout test || git checkout --orphan test

          # Clean everything, including previously ignored files
          git rm -rf . --ignore-unmatch
          rm -rf *

          # Copy in new files from temp-dist
          cp -r temp-dist/* .
          rm -rf temp-dist

          # Commit and force push
          git add .
          git commit -m "Deploy to test branch from main"
          git push origin test --force
      
