name: Build and Deploy to gh-pages Branch
run-name: ${{ github.actor }} is deploying code to Github Pages 🚀

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Prepare dist for deployment
        run: |
          mkdir ../dist-temp
          cp -r dist/* ../dist-temp/
          echo "www.w3bl.com" > ../dist-temp/CNAME
          touch ../dist-temp/.nojekyll

      - name: Switch to gh-pages branch and deploy
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Clean up before switching
          git clean -fdx
          git checkout gh-pages || git checkout --orphan gh-pages

          # Remove all tracked files
          git rm -rf . --ignore-unmatch

          # Copy built files into repo
          cp -r ../dist-temp/* .
          rm -rf ../dist-temp

          # Commit and push
          git add .
          git commit -m "Deploy to gh-pages branch from main"
          git push origin gh-pages --force
