name: Deploy to Github Pages
run-name: ${{ github.actor }} is deploying code to Github Pages 🚀
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Setup Node.js environment
      - uses: actions/setup-node@v4

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the website
      - name: Build website
        run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

      # Deploy to local repo
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: test
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
