name: Deploy to Github Pages
run-name: ${{ github.actor }} is deploying code to Github Pages 🚀
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: List directories in a directory
        run: |
          echo "Listing directories:"
          for dir in $(ls -d */); do
            echo $dir
          done

      # Deploy to local repo
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: test
          FOLDER: ./dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
